In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6])

In [7]:
newarr = np.array_split(arr,5)

print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [8]:
import numpy as np

arr = np.array([1,2,3,4,5,4,4])

x = np.where(arr==4)

print(x)

(array([3, 5, 6]),)


In [12]:
arr = np.random.randint(1,100,(1,5))

In [15]:
y = np.where(arr%2==0)

In [20]:
print(y)

(array([0, 0]), array([1, 4]))


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

x = np.where(arr%2==1)

print(x)

(array([0, 2, 4, 6]),)


In [3]:
arr = np.array([6,7,8,9])

x = np.searchsorted(arr,7)

print(x)

1


In [22]:
arr = np.array([2,3,1,51,23,6,21,33,55])

x = np.searchsorted(arr, 3, side='right')

print(x)

3


In [24]:
arr = np.array([6,7,8,9,4,31])

x = np.searchsorted(arr, 6, side='right')

print(x)

1


In [26]:
arr = np.array([1,3,5,7])

x = np.searchsorted(arr,[2,4,6,8])

print(x)

[1 2 3 4]


In [27]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

arr2 = np.array_split(arr,3)

print(arr2)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [28]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [29]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [30]:
import numpy as np

arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

newarr = np.array_split(arr,3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [31]:
arr = np.array([3,2,0,1])

print(np.sort(arr))

[0 1 2 3]


In [32]:
arr = np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [33]:
arr = np.array([True,False,True])

print(np.sort(arr))

[False  True  True]


In [34]:
arr = np.array([[3,2,4],[5,0,1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [36]:
arr  = np.array([41,42,43,44])

x = [True,True,True,False]

newarr = arr[x]

print(newarr)

[41 42 43]


In [58]:
arr = np.array([39,40,41,42,43,44,45])

filter_arr = []
filter_arr2 = []

for element in arr:
    if element >= 42:
        filter_arr.append(True)
    elif element < 42:
        filter_arr.append(False)
        filter_arr2.append(True)
    else:
        filter_arr.append(False)
        filter_arr2.append(False)

newarr = arr[filter_arr]
newarr2 = arr[filter_arr2]

print(filter_arr)
print(f' this one is more than or equal 42:{newarr}')
print(f' this one is lower than of 42:{newarr2}')


IndexError: boolean index did not match indexed array along axis 0; size of axis is 7 but size of corresponding boolean axis is 3

In [59]:
arr = np.array([39, 40, 41, 42, 43, 44, 45])

filter_arr = arr >= 42
filter_arr2 = arr < 42

newarr = arr[filter_arr]
newarr2 = arr[filter_arr2]

print(filter_arr)

print(f'this one is more than or equal to 42: {newarr}')
print(f'this one is less than to 42:{newarr2}')

[False False False  True  True  True  True]
this one is more than or equal to 42: [42 43 44 45]
this one is less than to 42:[39 40 41]
