In [51]:
import numpy as np


arr = np.array([41,42,43,44])
x = [True,False,True,False]
newaar = arr[x]

print(newaar)

[41 43]


In [52]:
arr = np.array([42,2,13,21,88,91,46,47])

filter_arr = []

for element in arr:

    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newaar = arr[filter_arr]

print(filter_arr)
print(newaar)

[False, False, False, False, True, True, True, True]
[88 91 46 47]


In [53]:


arr = np.array([1,2,3,4,5,6,7])

filter_arr = []
for item in arr:
    
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newaar = arr[filter_arr]

In [54]:
print(filter_arr)
print(newaar)

[False, False, False, False, False, False, False]
[]


In [55]:
arr = np.array([41,42,43,44])
filter_arr = arr > 42
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [56]:
arr = np.array([1,2,3,4,5,6,7,84,1,33,222])

filter_arr = arr % 2 == 0
newarr = arr[filter_arr]

print(filter_arr)
print(arr[~filter_arr])

[False  True False  True False  True False  True False False  True]
[ 1  3  5  7  1 33]


In [57]:
from numpy import random

In [63]:
x = random.choice([2,9,20,9], p=[0.1, 0.3, 0.6, 0.0],size=(1000))
print(x)

[20  9 20 20 20 20 20  9  9 20 20 20  9 20 20 20 20 20 20 20  9  2  9  9
  9  2  9  9 20  2 20 20 20 20 20 20  9  9  9 20 20 20  9 20 20 20  9  9
 20 20  2  9 20  2  9  9 20 20 20  9 20 20  9 20 20 20  2 20  9 20 20  9
 20 20 20 20 20  2 20 20 20 20 20 20  9 20 20  9 20 20 20 20  9  9 20 20
 20 20 20 20  9  9 20 20 20 20 20 20  2 20 20 20 20 20  2  9  9  2 20  9
 20 20 20 20 20 20 20 20 20 20 20  2 20  9  9 20 20 20 20  2 20  2  9 20
 20 20 20 20  9 20 20 20 20  9  9 20  9 20 20  9  2 20 20 20  9  9 20  9
  9 20 20 20  9  9 20  2 20 20 20 20  9 20 20  9  9  9 20 20  2  9  2 20
 20 20 20 20  9  9  9  9  9 20  9 20  9 20 20 20  9  9 20 20 20  9  9 20
 20  9 20  9  9  9  9 20  2 20 20 20  9  9 20  9 20 20 20 20 20 20  9 20
  9 20 20 20  9  2  9 20  9 20  9 20 20 20 20  2 20 20  9  9 20  9  9 20
 20  2  9 20 20 20 20  9  9 20  9 20 20 20  9 20  9  9 20  2  9 20  9 20
 20 20 20  9  9 20  2  9 20  9  2  9 20 20 20  9  2 20 20  9 20  2  9  9
 20 20 20  9  2 20  9 20  2 20 20 20  9 20  2 20  9

In [65]:
from numpy import random

x = random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0], size=(3,5))
print(x)

[[5 7 5 7 7]
 [7 5 7 7 7]
 [7 5 7 7 5]]


In [66]:
arr = np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [67]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [69]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [71]:
import numpy as np 

arr = np.array([1,2,3,4,5,4,4])

x = np.where(arr==4)

print(x)

(array([3, 5, 6]),)


In [72]:
arr = np.array([1,2,3,4,5,6,7,8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [73]:
x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


In [75]:
arr = np.array([6,7,8,9,10,22,11,13])

x = np.searchsorted(arr,10)

print(x)

4


In [78]:
arr = np.array([6,7,8,9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2
