In [1]:
import numpy

speed = [99,86,87,111,86,103,87,94,78,77,85,86]

In [2]:
x = numpy.mean(speed)

In [3]:
print(x)

89.91666666666667


In [4]:
import numpy.ma as ma

data = ma.array([1,2,3,-1],mask=[0,0,0,1])

In [5]:
print(data)

[1 2 3 --]


In [6]:
import numpy as np
import numpy.ma as ma

data = np.array([1,2,3,-999,5])
masked = ma.masked_equal(data,-999)

print(masked)

data2 = np.array([1,2,3,4,5,6,7])
masked2 = ma.masked_equal(data2,5)

print(masked2)

[1 2 3 -- 5]
[1 2 3 4 -- 6 7]


In [7]:
masked = ma.masked_equal([1,2,-999,4],-999)
print(masked.mean())

2.3333333333333335


In [8]:
print(masked.mask)

[False False  True False]


In [9]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])
result = a + b
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [10]:
a = np.arange(6).reshape(2,3)
b = a.ravel()
b[3] = 99
print(a)

[[ 0  1  2]
 [99  4  5]]


In [11]:
a = np.arange(6).reshape(2,3)
b = a.ravel()
b[5] = 99
print(a)

[[ 0  1  2]
 [ 3  4 99]]


In [12]:
import numpy as np
import numpy.ma as ma

data = np.array([1,2,3,-999,5])
mask = np.array([False,False,False,True,False])
masked_array = ma.masked_array(data,mask=mask)

print(masked_array)

[1 2 3 -- 5]


In [13]:
mean_value = ma.mean(masked_array)

In [14]:
print(mean_value)

2.75


In [15]:
data = np.array([1,2,3,4,5])
masked_array = ma.masked_where(data > 3 , data)

In [16]:
print(masked_array)

[1 2 3 -- --]


In [17]:
import numpy as np

In [18]:
x = np.float32(1.0)


In [19]:
x

1.0

In [20]:
y = np.int_([1,2,4])

In [21]:
y

array([1, 2, 4])

In [22]:
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,3.0])

a * b

array([2., 4., 9.])

In [23]:
a = np.array([1.0,2.0,3.0])

b = 2.0

a * b

array([2., 4., 6.])

In [24]:
A = np.ones((2,3,4))
B = np.arange(4)

result = A + B

print(result.shape)

(2, 3, 4)


In [25]:
a = np.arange(3).reshape(3,1)
b = np.arange(4).reshape(1,4)

In [26]:
result = a + b

In [27]:
print(result)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


In [28]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [29]:
a = np.arange(6)
a2 = a[np.newaxis,:]
a2.shape

(1, 6)

In [30]:
a = np.array([1,2,3,4,5,6])

In [31]:
print(a)

[1 2 3 4 5 6]


In [32]:
import numpy as np

In [33]:
a = np.array([1,2,3])

In [34]:
np.zeros(2)

array([0., 0.])

In [35]:
np.ones(2)

array([1., 1.])

In [36]:
np.empty(2)

array([1., 1.])

In [37]:
np.arange(4)

array([0, 1, 2, 3])

In [38]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [39]:
arr = np.array([2,1,5,3,7,4,6,8])

In [40]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [42]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [44]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [46]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [47]:
b = a.reshape(1,2)

ValueError: cannot reshape array of size 6 into shape (1,2)

In [ ]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis,:]
a2.shape

(1, 6)

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])

In [ ]:
a % 2 == 0

array([False,  True, False,  True, False,  True])

In [ ]:
a[a % 2 == 0]

array([2, 4, 6])

In [ ]:
divisible_by_2 = a[a % 2 == 0]

In [ ]:
print(divisible_by_2)

[2 4 6]


In [ ]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,10])

In [ ]:
a[a > 5]

array([ 6,  7,  8, 10])

In [ ]:
a[a % 3 == 0]

array([3, 6])

In [ ]:
a[(a >= 4) & (a <= 8)]

array([4, 5, 6, 7, 8])

In [ ]:
a[a % 2 != 0]

array([1, 3, 5, 7])

In [ ]:
data = np.array([1,2])

In [ ]:
ones = np.ones(2,dtype=int)

In [ ]:
data + ones

array([2, 3])

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a.sum()

10

In [ ]:
b = np.array([[1,1],[2,2]])

In [ ]:
b.sum(axis=0)

array([3, 3])

In [ ]:
data = np.array([[1,2],[3,4],[5,6]])

In [ ]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b = np.array([[1,2,3],[4,5,6]])

In [ ]:
b[b >3]

array([4, 5, 6])

In [ ]:
a = np.array([1,2,3,4,5])

np.where(a % 2 == 0,'even','odd')

array(['odd', 'even', 'odd', 'even', 'odd'], dtype='<U4')

In [ ]:
a = np.array([10,15,0,22,0,30])

In [ ]:
idx = np.nonzero(a)

In [ ]:
print(idx)

(array([0, 1, 3, 5], dtype=int64),)


In [ ]:
a = np.array([1,2,3,4,5,6])

In [ ]:
even = a % 2 == 0

In [ ]:
print(even)

[False  True False  True False  True]


In [ ]:
not_even = ~even

In [ ]:
print(a[not_even])

[1 3 5]


In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

In [ ]:
print(a[a >3])

[4 5 6]


In [ ]:
a = np.array([[10,20],
             [30,40],
             [50,60]])

In [ ]:
print(a)

[[10 20]
 [30 40]
 [50 60]]


In [ ]:
rows = a[a[:,0] > 25]

In [ ]:
print(rows)

[[30 40]
 [50 60]]


In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

In [ ]:
np.sum(a)

21

In [ ]:
np.sum(a,axis=0)

array([5, 7, 9])

In [ ]:
np.sum(a,axis=1)

array([ 6, 15])

In [ ]:
np.mean(a,axis=0)

array([2.5, 3.5, 4.5])

In [ ]:
np.mean(a,axis=1)

array([2., 5.])

In [ ]:
np.argmax(a)

5

In [ ]:
np.argmax(a,axis=0)

array([1, 1, 1], dtype=int64)

In [ ]:
np.argmax(a,axis=1)

array([2, 2], dtype=int64)

In [ ]:
a = np.array([1,2,3,4,5,6])

b = a.reshape(2,3)

In [ ]:
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = np.array([[10,20,30],
                 [40,50,60]])

In [ ]:
df = pd.DataFrame(data,columns=['A','B','C'])

print(df)

    A   B   C
0  10  20  30
1  40  50  60


In [ ]:
df['Flag'] = np.where(df['C'] > 40, 'High','Low')

In [ ]:
print(df)

    A   B   C  Flag
0  10  20  30   Low
1  40  50  60  High


In [ ]:
df['RowMax'] = np.max(df[['A','B','C']].values, axis=1)

In [ ]:
print(df)

    A   B   C  Flag  RowMax
0  10  20  30   Low      30
1  40  50  60  High      60


In [ ]:
row_vector = np.array([1,2,3])

In [ ]:
df[['A','B','C']] = df[['A','B','C']] - row_vector

In [ ]:
print(df)

    A   B   C  Flag  RowMax
0   9  18  27   Low      30
1  39  48  57  High      60


In [ ]:
mask = df['A'] > 5

filtered = df[mask]

In [ ]:
filtered = df[np.array([True,True])]

In [ ]:
print(filtered)

    A   B   C  Flag  RowMax
0   9  18  27   Low      30
1  39  48  57  High      60


In [48]:
import pandas as pd
import numpy as np

In [49]:
df = pd.read_csv('data.csv')

In [54]:
data_np = df[['Age','Salary']].to_numpy()

In [53]:
print(data_np)

[['Alice' 25 50000]
 ['Bob' 30 60000]
 ['Carol' 35 70000]]


In [55]:
normalized = (data_np - data_np.mean(axis=0)) / data_np.std(axis=0)

In [57]:
mean_val = np.mean(df[['Age','Salary']],axis=0)
std_vals = np.std(df[['Age','Salary']],axis=0)

In [58]:
print(mean_val)
print(std_vals)

Age          30.0
Salary    60000.0
dtype: float64
Age          4.082483
Salary    8164.965809
dtype: float64


In [59]:
df['Salary'] = np.where(df['Salary'] > 55000,55000,df['Salary'])

In [60]:
print(df)

    Name  Age  Salary
0  Alice   25   50000
1    Bob   30   55000
2  Carol   35   55000


In [62]:
def custom_score(x):
    return np.sqrt(x['Age'] * x['Salary'])

df['Score'] = df.apply(custom_score,axis=1)

In [63]:
print(df)

    Name  Age  Salary        Score
0  Alice   25   50000  1118.033989
1    Bob   30   55000  1284.523258
2  Carol   35   55000  1387.443693


In [64]:
features = df[['Age','Salary']].to_numpy()
weights = np.array([[0.1],[0.0005]])

In [65]:
prediction = features @ weights
df['Prediction'] = prediction

In [66]:
print(df)

    Name  Age  Salary        Score  Prediction
0  Alice   25   50000  1118.033989        27.5
1    Bob   30   55000  1284.523258        30.5
2  Carol   35   55000  1387.443693        31.0


In [67]:
diff = df[['Age','Salary']].to_numpy() - np.array([30,60000])
df[['Age_diff','Salary_diff']] = diff

In [68]:
print(df)

    Name  Age  Salary        Score  Prediction  Age_diff  Salary_diff
0  Alice   25   50000  1118.033989        27.5        -5       -10000
1    Bob   30   55000  1284.523258        30.5         0        -5000
2  Carol   35   55000  1387.443693        31.0         5        -5000


In [69]:
mask =(df['Age'] > 27) & (df['Salary'] < 65000)
filtered_df = df[mask]

In [70]:
print(filtered_df)

    Name  Age  Salary        Score  Prediction  Age_diff  Salary_diff
1    Bob   30   55000  1284.523258        30.5         0        -5000
2  Carol   35   55000  1387.443693        31.0         5        -5000
