In [2]:
import torch 


In [3]:
x = torch.tensor([[1,2],[3,4]])

In [4]:
print(x)

tensor([[1, 2],
        [3, 4]])


In [5]:
import numpy as np

In [6]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [7]:
arr = np.array([10,20,30,40])
indices = [0,2]

In [8]:
import pandas as pd

arrays = [
          ['A','A','B','B'],
          [1,2,1,2]
          ]

In [10]:
index = pd.MultiIndex.from_arrays(arrays,names=('Group','Index'))
df = pd.DataFrame({'Value':[10,20,30,40]},index=index)

In [12]:
print(df.loc['B'])

       Value
Index       
1         30
2         40


In [13]:
df = pd.DataFrame({
    'Team':['A','A','B','B'],
    'Points':[10,20,15,25],
    'Assist':[5,7,9,11]
})

print(df.groupby('Team').agg({
    'Points':['sum','mean'],
    'Assist':'max'
}))

     Points       Assist
        sum  mean    max
Team                    
A        30  15.0      7
B        40  20.0     11


In [14]:
df = pd.DataFrame({'x':[1,2,3]})

In [15]:
df['squared'] =df['x'].apply(lambda  x:x**2)

In [16]:
df['total'] = df.apply(lambda row:row['x'] + row['squared'],axis=1)

In [17]:
print(df)

   x  squared  total
0  1        1      2
1  2        4      6
2  3        9     12


In [19]:
df1 = pd.DataFrame({'ID':[1,2],'Name':['Alice','Bob']})
df2 = pd.DataFrame({'ID':[1,2],'Score':[85,90]})
merged = pd.merge(df1,df2,on='ID')

In [20]:
print(merged)

   ID   Name  Score
0   1  Alice     85
1   2    Bob     90


In [22]:
df = pd.DataFrame({
    'City':['NY','NY','LA','LA'],
    'Year':[2020,2021,2020,2021],
    'Sales':[100,150,200,250]
})

pivot = df.pivot_table(values='Sales',index='City',columns='Year')

print(pivot)

Year   2020   2021
City              
LA    200.0  250.0
NY    100.0  150.0


In [23]:
import pandas as pd

data = {
    'OrderID': [1001, 1002, 1003, 1004, 1005, 1006],
    'Customer': ['Alice', 'Bob', 'Alice', 'David', 'Bob', 'Alice'],
    'Region': ['North', 'South', 'North', 'East', 'South', 'North'],
    'Product': ['Laptop', 'Tablet', 'Phone', 'Laptop', 'Phone', 'Tablet'],
    'Quantity': [1, 3, 2, 1, 1, 4],
    'UnitPrice': [1200, 400, 600, 1200, 600, 400],
    'Discount': [0.1, 0.0, 0.05, 0.1, 0.2, 0.0],
    'Date': pd.to_datetime(['2024-01-15', '2024-01-16', '2024-01-17', '2024-01-18', '2024-01-19', '2024-01-20'])
}

df = pd.DataFrame(data)

In [45]:
#Total revenue per customer (consider quantity × unit price × (1 - discount))

df['Revenue'] = df['Quantity'] * df['UnitPrice'] * (1- df['Discount'] )
revenue_per_customer = df.groupby('Customer')['Revenue'].sum()
print(revenue_per_customer)

Customer
Alice    3820.0
Bob      1680.0
David    1080.0
Name: Revenue, dtype: float64


In [60]:
popular_product = df.groupby('Product')['Quantity'].sum()
print(pd.DataFrame(popular_product))



         Quantity
Product          
Laptop          2
Phone           3
Tablet          7


In [63]:
average_discount = df.groupby('Region')['Discount'].sum()

In [64]:
print(pd.DataFrame(average_discount))

        Discount
Region          
East        0.10
North       0.15
South       0.20


In [67]:
#Total revenue per product in the North region

In [73]:
north_df = df[df['Region']=='North']

In [77]:
print(north_df)
print(f"total revenue of North: {north_df['Revenue'].sum()}")

   OrderID Customer Region Product  Quantity  UnitPrice  Discount       Date  \
0     1001    Alice  North  Laptop         1       1200      0.10 2024-01-15   
2     1003    Alice  North   Phone         2        600      0.05 2024-01-17   
5     1006    Alice  North  Tablet         4        400      0.00 2024-01-20   

   Revenue  
0   1080.0  
2   1140.0  
5   1600.0  
total revenue of North: 3820.0


In [ ]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Math': [85, 78, 92, 67, 88],
    'Science': [90, 76, 85, 70, 95],
    'English': [78, 80, 89, 60, 85]
}

df = pd.DataFrame(data)
df2 = pd.DataFrame(data)

In [111]:
df['Average'] = df[['Math','Science','English']].mean(axis=1)

KeyError: "None of [Index(['Math', 'Science', 'English'], dtype='object')] are in the [columns]"

In [86]:
print(df['Average'])

0    84.333333
1    78.000000
2    88.666667
3    65.666667
4    89.333333
Name: Average, dtype: float64


In [87]:
highest_math = df.loc[df['Math'].idxmax(),'Name']

In [88]:
print(highest_math)

Charlie


In [91]:
highest_science = df.loc[df['Science'].idxmax(),'Name']
print(f"highest science grade was {highest_science}")

highest science grade was Eva


In [92]:
avg_per_subject = df[['Math','Science','English']].mean()
print(pd.DataFrame(avg_per_subject))

            0
Math     82.0
Science  83.2
English  78.4


In [93]:
df['Passed'] = df['Average'] >= 75


In [95]:
print(df)

      Name  Math  Science  English    Average  Passed
0    Alice    85       90       78  84.333333    True
1      Bob    78       76       80  78.000000    True
2  Charlie    92       85       89  88.666667    True
3    David    67       70       60  65.666667   False
4      Eva    88       95       85  89.333333    True


In [97]:
science_std = np.std(df['Science'])

print(science_std)

9.10823802938856


In [98]:
import pandas as pd

data = {
    'Customer': ['Anna', 'Ben', 'Cathy', 'David', 'Ella'],
    'Item': ['Milk', 'Bread', 'Eggs', 'Milk', 'Bread'],
    'Quantity': [2, 1, 12, 1, 2],
    'Price_per_item': [1.50, 2.00, 0.20, 1.50, 2.00]
}

df = pd.DataFrame(data)

In [99]:
df['Total_Cost'] = df['Quantity'] * df['Price_per_item']

In [100]:
print(df)

  Customer   Item  Quantity  Price_per_item  Total_Cost
0     Anna   Milk         2             1.5         3.0
1      Ben  Bread         1             2.0         2.0
2    Cathy   Eggs        12             0.2         2.4
3    David   Milk         1             1.5         1.5
4     Ella  Bread         2             2.0         4.0


In [102]:
print(f"total cost of all customer: {df['Total_Cost'].sum()}")

total cost of all customer: 12.9


In [104]:
total_milk = df[df['Item']=='Milk']['Quantity'].sum()

In [105]:
print(total_milk)

3


In [106]:
#most spend the most

most_spend = df.loc[df['Total_Cost'].idxmax(),'Customer']

In [107]:
most_spend

'Ella'

In [109]:
avg_price_item = df[['Milk', 'Bread', 'Eggs', 'Milk', 'Bread']].mean()


KeyError: "None of [Index(['Milk', 'Bread', 'Eggs', 'Milk', 'Bread'], dtype='object')] are in the [columns]"