In [1]:
import numpy as np

In [6]:
arr = np.array([4,2,3,4,5,4,4])

In [7]:
print(arr)

[4 2 3 4 5 4 4]


In [8]:
x = np.where(arr == 4)

In [9]:
print(x)

(array([0, 3, 5, 6], dtype=int64),)


In [10]:
arr = np.array([1,2,3,4,5,6,7,8])

In [ ]:
x = np.where(arr% 2== 0)

In [11]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

In [18]:
x = np.where(arr%2 == 0)

In [19]:
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [20]:
arr = np.array([1,2,3,4,5,6,7,8])

x = np.where(arr%2 == 1)

In [21]:
import numpy as np

arr = np.array([6,7,8,9])


x = np.searchsorted(arr,7)

print(x)

1


In [25]:
import numpy as np

arr = np.array([6,7,8,9])

x = np.searchsorted(arr,7,side='right')

print(x)

2


In [26]:
import numpy as np

arr = np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [27]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

In [28]:
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [29]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])


for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [ ]:
data = np.array([1.5,2.0,3.5])
mean = np.mean(data)
std = np.std(data)


z_scores = (data - mean) / std