In [2]:
import numpy as np

In [ ]:
data = np.array([1.0,2.0])


In [4]:
data * 1.6

array([1.6, 3.2])

In [5]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [8]:
a.sum()
a.min()
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [9]:
x = np.array([('Rex',9,91.0),('Fido',3,27.0)],
             dtype=[('name','U10'),('age','i4'),('weight','f4')])

In [10]:
x

array([('Rex', 9, 91.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [1]:
import numpy as np
z = np.arange(10)

In [2]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
y = z[1:3]

In [4]:
y

array([1, 2])

In [26]:
y[1:3] = [10,11]

ValueError: could not broadcast input array from shape (2,) into shape (1,)

In [1]:
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
y = x[1:3]

In [5]:
y

array([1, 2])

In [6]:
x[1:3] = [10,11]

In [7]:
x

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [8]:
y

array([10, 11])

In [9]:
x = np.arange(9).reshape(3,3)

In [10]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
y = x[[1,2]]

In [12]:
y

array([[3, 4, 5],
       [6, 7, 8]])

In [13]:
y.base is None

True

In [14]:
x[[1,2]] = [[10,11,12],[13,14,15]]

In [15]:
x

array([[ 0,  1,  2],
       [10, 11, 12],
       [13, 14, 15]])

In [16]:
y

array([[3, 4, 5],
       [6, 7, 8]])

In [21]:
v = np.ones((2,3))
b = x.T
b

array([[ 0, 10, 13],
       [ 1, 11, 14],
       [ 2, 12, 15]])

In [22]:
import pandas as pd

In [25]:
df1 = pd.DataFrame({
    "A":["A0","A1","A2","A3"]
    
})

In [28]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)

In [29]:
df2 = pd.DataFrame({
    "A":["A4","A5","A6","A7"],
    "B":["B4","B5","B6","B7"],
    "C":["C4","C5","C6","C7"],
    "D":["D4","D5","D6","D7"],
},
    index = [4,5,6,7],
)

In [30]:
df3 = pd.DataFrame({
    "A":["A8","A9","A10","A11"],
    "B":["B8","B9","B10","B11"],
    "C":["C8","C9","C10","C11"],
    "D":["D8","D9","D10","D11"],
    },
    index = [8,9,10,11],
)

In [31]:
frames = [df1,df2,df3]

In [32]:
result = pd.concat(frames)

In [33]:
result 

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [35]:
df4 = pd.DataFrame({
    "B":["B2","B3","B6","B7"],
    "D":["D2","D3","D6","D7"],
    "F":["F2","F3","F6","F7"]
}, index = [2,3,6,7]
)

In [36]:
result = pd.concat([df1,df4], axis = 1)

In [37]:
result

A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7