In [1]:
class Meta(type):
    def __new__(cls,name,bases,dct):
        print(f'Creating class:{name}')
        dct['new_attribute'] = 42
        return super().__new__(cls,name,bases,dct)

class MyClass(metaclass=Meta):
    pass

print(MyClass.new_attribute)

Creating class:MyClass
42


In [2]:
class EnforceCamelCase(type):
    def __new__(cls,name,bases,dct):
        if not name[0].isupper():
            raise TypeError('Class name must start with an uppercase letter!')
        return super().__new__(cls,name,bases,dct)

class ValidClass(metaclass=EnforceCamelCase):
    pass

In [4]:
class SingletonMeta(type):
    _instances = {}

    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super().__call__(*args, **kwargs)
        return cls._instances[cls]

class Singleton(metaclass=SingletonMeta):
    pass

a = Singleton()
b = Singleton()

print(a is b)  # Output: True

True


In [ ]:
class ReadOnly:
    def __init__(self,value):
        self._value = value

    def __get__(self.instance,owner):
        return self._value
    
    def __set__(self,instance,value):
        raise  AttributeError('This attribute is read-only!b ')

In [5]:
from functools import lru_cache

@lru_cache(maxsize=3)
def expensive_function(n):
    print(f'Computing {n}...')
    return n * n

print(expensive_function(4))
print(expensive_function(4))
print(expensive_function(5))

Computing 4...
16
16
Computing 5...
25


In [6]:
class MyContext:
    def __enter__(self):
        print('Entering Context')
        return self
    
    def __exit__(self,exc_type,exc_value,traceback):
        print('Existing Context')

with MyContext():
    print('Inside Context')

Entering Context
Inside Context
Existing Context


In [7]:
class A:
    def show(self):
        print('A')

class B(A):
    def show(self):
        print('B')
        super().show()

class C(A):
    def show(self):
        print('C')
        super().show()

class D(B,C):
    def show(self):
        print('D')
        super().show()

obj = D()
obj.show()

D
B
C
A


In [38]:
import numpy as np

arr = np.ones((5,5))
print(arr)

arr2 = np.random.randint(1, 99, (17))
convert_negative_one = np.where(arr2 % 2 == 0, -1, arr2)

print(convert_negative_one)

arr3 = np.array([[10, 20, 30], 
                [5,  25, 35], 
                [50, 15, 45]])
arr3_max = []

for i in arr3:
    try:
        arr3_max.append(np.max(i))
    except:
        print('well')

print(arr3_max)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[63 -1 -1 19 -1 25 69 33 75 -1 -1 -1 27 -1 -1 31 75]
[30, 35, 50]


In [ ]:
import numpy as np

def normalize_2d(matrix):
    norm = np.linalg.norm(matrix)
    matrix = matrix/norm
    return matrix


array = np.arange(16)-2

matrix = array.shape(4,4)
print(matrix)
normalize_matrix = normalize_2d(matrix)
print(normalize_matrix)

TypeError: 'tuple' object is not callable

In [68]:
arr = np.full((6,6),1)
print(arr)
arr2 = np.eye(6)
print(arr2)

arr3 = np.array([10,20,30,40,50])
print(arr3[::-1])

arr5 = np.array([-5,-3,-1,0,2,4,6])
replace_arr5 = np.where(arr5 % 2 == 0 ,0 ,arr5)
print(replace_arr5)

arr6 = np.random.randint(1,100,(3,3))
print(arr6)

arr7 = np.array([1,2,2,3,4,4,5,6,6])
print(np.unique(arr7))

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[50 40 30 20 10]
[-5 -3 -1  0  0  0  0]
[[18 99 75]
 [92 47 28]
 [83 92 61]]
[1 2 3 4 5 6]


In [69]:
numbers  = [9,34,11,-4,27]

max_number = max(numbers)
print(max_number)

34


In [70]:
language = ['Python','C Programming','Java','JavaScript']
largest_string = max(language)

print(largest_string)

Python


In [2]:
import numpy as np
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [3]:
unique_values = np.unique(a)

In [4]:
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [6]:
unique_values,indices_list = np.unique(a,return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [8]:
unique_values, occurrence_count = np.unique(a,return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [18]:
a_2d = np.random.randint(1,10,(4,4))
print(a_2d)
unique_values = np.unique(a_2d)
print(unique_values)

[[8 1 9 2]
 [9 8 8 7]
 [8 9 2 8]
 [1 3 4 1]]
[1 2 3 4 7 8 9]


In [21]:
unique_rows = np.unique(a_2d,axis=1)
print(unique_rows)

[[1 2 8 9]
 [8 7 9 8]
 [9 8 8 2]
 [3 1 1 4]]


In [22]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [23]:
unique_values = np.unique(a_2d)

In [24]:
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [25]:
unique_rows = np.unique(a_2d, axis=0)

In [26]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [2]:
import numpy as np

a1d = np.array([1,2,3,4])
a2d = np.array([[1,2],[3,4]])
a3d = np.array([[1,2],[3,4],[5,6],[7,8]])

In [3]:
np.array([127,128,129],dtype=np.int8)

C:\Users\francis\AppData\Local\Temp\ipykernel_28308\2898415833.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127,128,129],dtype=np.int8)
C:\Users\francis\AppData\Local\Temp\ipykernel_28308\2898415833.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127,128,129],dtype=np.int8)


array([ 127, -128, -127], dtype=int8)

In [7]:
s1 = np.arange(10)
print(s1)
np.arange(2,10,dtype=float)
np.arange(2,3,0.1)

[0 1 2 3 4 5 6 7 8 9]


array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [8]:
sa = np.eye(9)


In [9]:
print(sa)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [13]:
asa = np.eye(100,100)
print(asa)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [15]:
asd = np.diag([1,2,3])
print(asd)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [16]:
ndarray = np.zeros((2,3))
print(ndarray)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:

aa = np.array([1,2,3,4,5,6])
b = aa[:2]
b += 1

print('a =',aa, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]
