In [1]:
import torch

In [2]:
x = torch.rand(5,3)

In [4]:
print(x)

tensor([[0.4051, 0.1164, 0.5080],
        [0.0897, 0.7294, 0.5367],
        [0.2930, 0.8573, 0.9037],
        [0.8390, 0.0872, 0.6761],
        [0.4051, 0.1791, 0.6978]])


In [5]:
# check gpu driver
torch.cuda.is_available()

False

In [ ]:
x = torch.randn(5, requires_grad=True)
y = x.pow(2)
print(x.equal(y.grad_fn._saved_self ))  # True
print(x is y.grad_fn._saved_self)  # True

True
True


In [12]:
x = torch.randn(5,requires_grad=True)
y = x.exp()
print(y.equal(y.grad_fn._saved_result))
print(y is y.grad_fn._saved_result)

True
False


In [16]:
def train_fn():
    x = torch.ones(5,5, requires_grad=True)
    y =(x + 3) * (x + 4) * 0.5
    y.sum().backward()

In [22]:
threads = []
threading = []
import threading

In [ ]:
for _ in range(10): # this will loop 10 times
    p = threading.Thread(target=train_fn,args=())
    p.start()
    threads.append(p)

for p in threads:
    p.join()

In [29]:
# same shape are always broadcastable
x = torch.empty(5,7,3)
y = torch.empty(5,7,3)
print(x,y) # this will print pytorch shape

tensor([[[9.2914e+15, 1.8189e-42, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

       

In [31]:
xx = torch.empty((0,))
yy = torch.empty(2,2)
# x and y not broadcastable since x does not have 1 least dimension
print(xx,yy)

tensor([]) tensor([[9.0792e+15, 1.8189e-42],
        [2.3694e-38, 9.2196e-41]])


In [ ]:
# can line up trailing dimensions
xxx = torch.empty(5,3,4,1)
yyy = torch.empty( 3,1,1)
print(xxx,yyy)

tensor([[[[9.5001e+15],
          [1.8189e-42],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0

In [33]:
xxxx = torch.empty(5,2,4,1)
yyyy = torch.empty(  3,1,1)
print(xxxx,yyyy)


tensor([[[[9.6408e+15],
          [1.8189e-42],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00],
          [0.0000e+00],
          [0.0000e+00]]]]) tensor([[[9

In [37]:
x1 = torch.empty(5,1,4,1)
y1 = torch.empty(3,1,1)
size1= (x1+y1).size()
size2 = torch.Size([5,3,4,1])
print(size1)
print(size2)

torch.Size([5, 3, 4, 1])
torch.Size([5, 3, 4, 1])


In [39]:
x = torch.empty(5,3,4,1)
y = torch.empty(3,1,1)
(x.add_(y)).size()

torch.Size([5, 3, 4, 1])

In [40]:
x =  torch.empty(1,3,1)
y = torch.empty(3,1,7)
(x.add_(y)).size()

RuntimeError: output with shape [1, 3, 1] doesn't match the broadcast shape [3, 3, 7]

In [42]:
px = torch.tensor([1,2,3,4,5,6,7],
                  [2,3,4,5,7,8])
y = px.pow(2)

print(y)

TypeError: tensor() takes 1 positional argument but 2 were given

In [43]:
x = torch.tensor([[1,2],[3,4]])

y = x.exp()
print(y)

tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])
