In [100]:
import numpy as np

In [101]:
a = np.array([1.0,2.0,3.0])

In [102]:
b = np.array([2.0,2.0,2.0])

In [103]:
a * b

array([2., 4., 6.])

In [104]:
a = np.array([1.0,2.0,3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [105]:
a = np.array([0.0,10.0,20.0,30.0])
b = np.array([1.0,2.0,3.0])

In [106]:
a[:,np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [107]:
from numpy import array,argmin, sqrt,sum


In [108]:
observation = array([111.0,188.0])

In [109]:
codes_d = np.array([
    [102.0, 203.0],
    [132.0, 192.0],
    [45.0, 155.0],
    [57.0, 173.0]  # Removed the extra element
])

In [110]:
diff = codes_d - observation

In [111]:
dist = sqrt(sum(diff**2,axis=-1))

In [112]:
argmin(dist)

np.int64(0)

In [113]:

# Define codes_d and observation
codes_d = np.array([
    [102.0, 203.0],
    [132.0, 192.0],
    [45.0, 155.0],
    [57.0, 173.0]
])
observation = np.array([111.0, 188.0])

# Calculate difference
diff = codes_d - observation

# Compute Euclidean distance
dist = np.sqrt(np.sum(diff**2, axis=-1))

print(dist)

[17.49285568 21.37755833 73.79024326 56.04462508]


In [114]:
import numpy as np

In [115]:
x = np.arange(10)

In [116]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
y = x[1:3]

In [118]:
y

array([1, 2])

In [119]:
x[1:3] = [10,11]

In [120]:
x

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [121]:
np.array(['hello','world'])

array(['hello', 'world'], dtype='<U5')

In [122]:
np.array([b'hello',b'world'])

array([b'hello', b'world'], dtype='|S5')

In [123]:
from numpy.dtypes import StringDType
import numpy as np

In [124]:
data = ['this is a longer string','short string']
arr = np.array(data,dtype=StringDType())
arr

array(['this is a longer string', 'short string'], dtype=StringDType())

In [125]:
dt = StringDType(na_object=None)

In [126]:
arr = np.array(['this array',None,'as an entry'])

In [127]:
np.sort(arr)

TypeError: '<' not supported between instances of 'NoneType' and 'str'

In [ ]:
arr = np.array(['hello','world'],dtype=StringDType())

In [ ]:
arr.astype(np.str_)

TypeError: cannot cast dtype StringDType() to <class 'numpy.dtypes.StrDType'>.

In [ ]:
arr.astype('U5')

array(['hello', 'world'], dtype='<U5')

In [ ]:
arr = np.array(["hello", "world"], dtype=StringDType())

In [ ]:
x = np.array([('Rex', 9, 104.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [ ]:
x

array([('Rex', 9, 104.), ('Fido', 3,  27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [ ]:
x[0]

np.void(('Rex', 9, 104.0), dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [ ]:
x['weight']

array([104.,  27.], dtype=float32)

In [ ]:
np.dtype([
        ('x','f'),
        ('y',np.float32),
        ('z','f',(2,2))
        ]
        )

dtype([('x', '<f4'), ('y', '<f4'), ('z', '<f4', (2, 2))])

In [ ]:
# manipulating and display structured datatypes

d = np.dtype([ 
    ('x','i8'),
    ('y','f4')
                ])

In [ ]:
d.names

('x', 'y')

In [ ]:
d['x']

dtype('int64')

In [ ]:
d.fields

mappingproxy({'x': (dtype('int64'), 0), 'y': (dtype('float32'), 8)})

In [ ]:
def print_offset(d):
    print('offsets:',[d.fields[name][1]for name in d.names])
    print('itemsize:',d.itemsize)

In [ ]:
print_offset(np.dtype('u1, u1, i4, u1, i8, u2'))

offsets: [0, 1, 2, 6, 7, 15]
itemsize: 17


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
# print only greater than 85

scores = np.array([85,92,78,90,88,76,95,89,84,91])


x = scores[scores>85]
print(x)
x_average = x.mean()
print(x_average)

[92 90 88 95 89 91]
90.83333333333333


In [ ]:
# temps convert to celcius to farh and print list and max and min

temps = np.array([30,32,29,36,28,33,31])

temp_list_container = []

for each in temps:
    try:
        f = each * (9/5) + 32
        temp_list_container.append(f)
    except Exception as e:
        print("An exception occurred  {e}")
    

print(temp_list_container)
print(f'this one is the max {max(temp_list_container)}')
print(f'this one is the min {min(temp_list_container)}')

[np.float64(86.0), np.float64(89.6), np.float64(84.2), np.float64(96.8), np.float64(82.4), np.float64(91.4), np.float64(87.80000000000001)]
this one is the max 96.8
this one is the min 82.4


In [155]:
import numpy as np

price = np.array([150, 200, 50, 500, 120, 90, 350, 75])

price_container = []

# Correct price increase
for x in price:
    try:
        f = x * 1.10  # Increase price by 10%
        price_container.append(f)
    except BaseException as e:
        print(f'An exception occurred: {e}')

# Convert list to NumPy array before adding
price_container = np.array(price_container)

added_price = price_container

# Get values greater than 200
exclude_data = added_price[added_price > 200]

print(added_price)
print(f'More than 200: {exclude_data}')


[165.  220.   55.  550.  132.   99.  385.   82.5]
More than 200: [220. 550. 385.]


In [163]:
# find value greater than the mean


data = np.array([10,25,35,40,50,60,75,85]) # array


mean_data = data.mean() # get the array mean

greater_than_mean = [k for k in data if k > mean_data] #get the greater than mean

converted_list = [int(x) for x in greater_than_mean] # convert our numpy as int

print(converted_list)
print(mean_data)



[50, 60, 75, 85]
47.5


In [ ]:
numbers = np.array([12, 45, 23, 78, 34, 55, 90, 27, 64, 81])

numbers = [int(x) for x in numbers]
# Count even numbers
even_count = [ k for k in numbers  if k   % 2  == 0]
print(even_count)
# Count odd numbers
odd_count = [ k for k in numbers  if k   % 2 != 0 ]

print(odd_count)


In [252]:
values = np.array([15,30,45,60,75,90])

value_container = []
print(values[0])

for x in values:
   x_list = int(x)
   value_container.append(x_list)

set1 =  np.subtract(np.array(value_container),np.array(min(value_container)))
set2 = np.array(max(value_container) - np.array(min(value_container)))

print(set1)
print(set2)

set3 = set1 / set2
print(set3)


15
[ 0 15 30 45 60 75]
75
[0.  0.2 0.4 0.6 0.8 1. ]


In [254]:
import numpy as np

values = np.array([15, 30, 45, 60, 75, 90])

value_container = []
print(values[0])

for x in values:
    x_list = int(x)
    value_container.append(x_list)

# Normalize the values using the correct formula
normalized = (np.array(value_container) - min(value_container)) / (max(value_container) - min(value_container))
print("Normalized values:", normalized)



15
Normalized values: [0.  0.2 0.4 0.6 0.8 1. ]


In [256]:
#reverse the array 

arr = np.array([5,10,15,20,25,30])

reversed_arr = arr[::-1]

print(reversed_arr)

[30 25 20 15 10  5]


In [267]:
data = np.array([1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7])

data_container = []
# populate our data 
for x in data:
    try:
        x_list = int(x)
        data_container.append(x_list)
    except:
        print()

for i in data_container:
    if data_container[i:11] == data_container[i:11]:
        data_container.pop
        print(data_container)
            
print(data_container)

#unique_element = [k for k in data if data_container[0:11] != ]
#print(unique_element)

[1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7]
[1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7]
[1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7]
[1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7]
[1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7]
[1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7]
[1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7]
[1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7]
[1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7]
[1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7]
[1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7]
[1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7]
[1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7]


In [268]:
import numpy as np

data = np.array([1, 2, 3, 4, 2, 3, 5, 6, 5, 7, 8, 7])

data_container = []
# Populate the list while ensuring no duplicates
for x in data:
    if x not in data_container:
        data_container.append(int(x))  # Append unique values only

print("Unique values:", data_container)

Unique values: [1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
arr = np.array([45, 78, 99, 23, 12, 88, 91, 100, 67])

container =  []


for x in arr:
    try:
        x_list = int(x)
        container.append(x_list)
    
    except:
        print()

largest = max(container)

second_largest = [k for k in container if k != largest]


print(f'this one is second largest{max(second_largest) }')
print(container)
print(largest)

# my answer to find second largest 


this one is second largest99
[45, 78, 99, 23, 12, 88, 91, 100, 67]
100


In [294]:
import numpy as np

arr = np.array([45, 78, 99, 23, 12, 88, 91, 100, 67])

# Find the largest number
largest = np.max(arr)

# Remove only ONE occurrence of the largest number and get the max of the rest
arr_filtered = arr[arr != largest]  # Remove only one occurrence

second_largest = np.max(arr_filtered)

print(f'This one is the second largest: {second_largest}')
print(f'All values: {arr}')
print(f'Largest value: {largest}')

This one is the second largest: 99
All values: [ 45  78  99  23  12  88  91 100  67]
Largest value: 100
