In [26]:
longest_word = "I love programming in Python"
longest_word = "Coding is fun, isn't it?"
words = longest_word.split()

res = ''

for words in words:
    if len(words) > len(res):
        res = words
print(res)

Coding


In [27]:
from collections import Counter

anagram1 = [
            'listen',
             "Silent"
            ]

if len(anagram1[0]) != len(anagram1[1]):
    print('NO')
else:
    if Counter(anagram1[0]) == Counter(anagram1[0]):  # compare character counts
        print("Yes")
    else:
        print("No")

Yes


In [28]:
class Parents:
    def greet(self):
        print('Hello From Parent')

class Child(Parents):
    pass

c = Child()
c.greet()

Hello From Parent


In [29]:
class Animal:
    def sound(self):
        print('Animals make sounds')

class Dog(Animal):
    def bark(self):
        print('Woof Woof')

d = Dog()
d.sound
d.bark

<bound method Dog.bark of <__main__.Dog object at 0x000001B1A6F0F9E0>>

In [30]:
import numpy as np

In [31]:
data = np.ones((5,5)) # filled with ones

In [32]:
data = np.ones((5,5)) # filled with ones
data[1:-1, 1:-1] = 0
print(data)
np.fill_diagonal(data,7)
print(data)
data_2 = sum(data)
result = sum(data_2)
print(result)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[7. 1. 1. 1. 1.]
 [1. 7. 0. 0. 1.]
 [1. 0. 7. 0. 1.]
 [1. 0. 0. 7. 1.]
 [1. 1. 1. 1. 7.]]
49.0


In [33]:
import numpy as np

# Step 1: Create a 5x5 matrix filled with ones
data = np.ones((5, 5))

# Step 2: Set the internal elements to 0
data[1:-1, 1:-1] = 0
print("Matrix with border as 1s and inner elements as 0s:")
print(data)

# Step 3: Replace the diagonal elements with 7
np.fill_diagonal(data, 7)
print("Matrix after replacing diagonal elements with 7:")
print(data)

# Step 4: Calculate the sum of all elements
result = np.sum(data)
print("Sum of all elements in the matrix:", result)


Matrix with border as 1s and inner elements as 0s:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Matrix after replacing diagonal elements with 7:
[[7. 1. 1. 1. 1.]
 [1. 7. 0. 0. 1.]
 [1. 0. 7. 0. 1.]
 [1. 0. 0. 7. 1.]
 [1. 1. 1. 1. 7.]]
Sum of all elements in the matrix: 49.0


In [34]:
import numpy as np
data = np.random.randint(10,100,(1,50))
print(data)

[[87 98 46 87 20 72 12 24 18 81 45 14 57 87 55 78 83 85 16 35 59 75 57 53
  71 56 19 30 64 20 10 39 57 60 66 96 51 15 21 78 52 70 71 10 21 61 52 55
  24 67]]


In [35]:
import numpy as np
data = np.random.randint(10,100,(1,50))
print(data)

new_data = data.reshape(5,10)
print(new_data)

count = [0,0,0,0,0,]

for x in range(5):
    x = 0

    print(max(new_data[x])) # this is wrong answere 

[[30 44 10 36 96 32 32 69 72 37 37 84 54 59 30 72 65 79 51 67 66 42 70 16
  31 18 94 63 11 68 14 70 13 14 95 95 16 89 31 31 68 57 33 32 52 34 48 69
  30 64]]
[[30 44 10 36 96 32 32 69 72 37]
 [37 84 54 59 30 72 65 79 51 67]
 [66 42 70 16 31 18 94 63 11 68]
 [14 70 13 14 95 95 16 89 31 31]
 [68 57 33 32 52 34 48 69 30 64]]
96
96
96
96
96


In [36]:
import numpy as np

# Generate a (1,50) array with random integers between 10 and 100
data = np.random.randint(10, 100, (1, 50))
print("Original Data:\n", data)

# Reshape to (5,10)
new_data = data.reshape(5, 10)
print("\nReshaped Data (5x10):\n", new_data)

# Create a list to store the max values (optional)
max_values = []

# Iterate through each row and print the maximum value
for x in range(5):
    max_value = max(new_data[x])  # Find max in row x
    max_values.append(max_value)  # Store in list (optional)
    print(f"Max of row {x}: {max_value}")

Original Data:
 [[91 37 12 82 66 46 65 21 30 68 20 89 25 84 95 95 61 63 25 33 81 64 44 68
  77 11 46 30 87 32 58 72 34 10 19 25 65 98 39 21 37 89 36 16 33 71 51 81
  26 93]]

Reshaped Data (5x10):
 [[91 37 12 82 66 46 65 21 30 68]
 [20 89 25 84 95 95 61 63 25 33]
 [81 64 44 68 77 11 46 30 87 32]
 [58 72 34 10 19 25 65 98 39 21]
 [37 89 36 16 33 71 51 81 26 93]]
Max of row 0: 91
Max of row 1: 95
Max of row 2: 87
Max of row 3: 98
Max of row 4: 93


Sure thing, here's another engaging NumPy challenge for you to try:

Problem: Manipulating Arrays and Mathematical Operations

Create a 6x6 matrix of random integers between 0 and 50.

Replace all values in the last row with their squared values.

Sort the matrix column-wise (i.e., each column should be sorted in ascending order).

Create a new array that contains only the unique values from the matrix and display them in ascending order.

Find the index of the maximum value in the entire matrix.

Take a shot at solving this, and let me know how it goes! 😊

In [132]:
import numpy as np

#create a 6x6 matrix of random interger between 0 and 50
data = np.random.randint(0,50,(6,6))
print(f'this is the matrix we have{data}')

# replace all values in the lasw row with quared  value
squared_data = data[5:] = data[5:] * data[5:]

print(f' this is the squared value last part {squared_data}')

# sort the data 
data_sorted = np.sort(data, axis=1)
print(f'this is the sorted data{data_sorted}')

#check unique value
unique_value = np.unique(data_sorted)
print(f'this is unique value{unique_value}')
#this will show the max of in value
max_value = max(unique_value)
print(f'this is the max value:  {max_value}')

this is the matrix we have[[12 32 13 11  1 22]
 [42 17 27 22  1  6]
 [49  4 41 20  3 17]
 [39 49 18 11 15 17]
 [11 29 34  7 27  0]
 [18 23 39  0 24 22]]
 this is the squared value last part [[ 324  529 1521    0  576  484]]
this is the sorted data[[   1   11   12   13   22   32]
 [   1    6   17   22   27   42]
 [   3    4   17   20   41   49]
 [  11   15   17   18   39   49]
 [   0    7   11   27   29   34]
 [   0  324  484  529  576 1521]]
this is unique value[   0    1    3    4    6    7   11   12   13   15   17   18   20   22
   27   29   32   34   39   41   42   49  324  484  529  576 1521]
this is the max value:  1521


In [143]:
import numpy as np

data = np.random.uniform(0.0, 1.0, size=(10, 10))  # 2x3 array with floats between 0.0 and 1.0
print(data)

[[6.94184802e-01 9.54031056e-02 9.04798017e-01 1.84960027e-01
  7.87756944e-01 2.47220686e-02 8.48761628e-01 4.70947390e-01
  4.67342761e-01 7.56146774e-01]
 [8.09207295e-01 7.87767351e-01 4.86489204e-02 8.08512674e-01
  9.37639062e-02 7.86078268e-01 1.25118363e-01 1.07847801e-04
  3.90138975e-01 5.15910271e-01]
 [1.97011372e-01 8.61393892e-01 9.76988767e-01 2.71975217e-01
  3.00611016e-01 4.18052655e-01 6.73455287e-01 3.70673189e-02
  8.50088495e-01 7.68764958e-01]
 [4.57742667e-01 8.86742287e-01 5.20015499e-01 1.32991987e-01
  1.08603247e-01 4.08042433e-01 1.04774783e-01 9.56171035e-02
  7.64518991e-01 8.00011829e-01]
 [5.37480783e-01 2.78350769e-01 7.20842730e-01 6.42452278e-01
  1.93296570e-01 7.56058052e-01 8.30558574e-01 8.16995201e-01
  1.90468750e-01 7.68809810e-01]
 [5.78682411e-01 4.84672974e-01 8.63486945e-01 7.42726272e-01
  8.91666578e-01 4.67624949e-01 9.70092227e-01 9.91449910e-01
  5.69616683e-01 3.37656181e-01]
 [6.15713129e-01 8.17478699e-01 4.51494778e-01 5.82381243e

Absolutely! Here's a fresh NumPy challenge for you:

**Problem: Matrix Transformation and Indexing**

1. Create a 10x10 matrix of random floating-point numbers between 0 and 1.
2. Extract:
   - All elements greater than 0.5.
   - The elements in the 3rd row and 5th column.
3. Replace all elements less than 0.2 with `0`.
4. Find the row with the maximum sum and return its index.

Let's see how you solve this one. Share your code when you're done or let me know if you need hints! 😊

In [156]:
import numpy as np

data = np.random.uniform(0.0, 1.0, size=(10, 10))  # 2x3 array with floats between 0.0 and 1.0
print(data)

#extract  more than 5
data2 = [x for x in data.flatten() if x > 0.5]
print(f'We get all more than 0.5 {data2}')

#extract only 3 row and 5 row
data3 = [data[2] + data[4]]
print(f'get the data 3 and 5 row{data3}')


data4 = [0 if x < 0.2 else x for x in data.flatten()] 
print(f'replace it with  zero: {data4}')

#get the maxx number 
data5 = np.max(data)
print(f'get the max number in array {data5}')

[[0.87481006 0.06828685 0.82416369 0.64806756 0.69427341 0.42314262
  0.12361287 0.19149137 0.78675545 0.66285326]
 [0.07318207 0.77673618 0.76669361 0.88121778 0.05431302 0.28733987
  0.50714292 0.97131315 0.55650759 0.89460775]
 [0.88096867 0.22973775 0.8770681  0.50633887 0.36404549 0.14863142
  0.15821672 0.05547817 0.90543384 0.34093529]
 [0.50203851 0.69148889 0.09661522 0.6961468  0.22034395 0.30173936
  0.17837256 0.80453928 0.97487759 0.3326935 ]
 [0.3518921  0.24280332 0.37678235 0.80639596 0.57417163 0.15276437
  0.38387331 0.64151015 0.50968051 0.7759825 ]
 [0.73342496 0.63074277 0.82802977 0.15633796 0.65088098 0.45969612
  0.90497486 0.20079442 0.74158422 0.778201  ]
 [0.17234071 0.1083806  0.50798918 0.88745471 0.94293708 0.11868595
  0.51975912 0.44089253 0.5302077  0.8894313 ]
 [0.3149725  0.20340616 0.42627645 0.30429958 0.54793395 0.17274194
  0.8097479  0.22298425 0.69569213 0.35714753]
 [0.36720258 0.57678511 0.06718354 0.52535003 0.96153046 0.68165266
  0.63884577

You're doing a great job tackling the problem! Let me point out a few issues and offer improvements to make your code work as intended:

### Observations and Fixes:
1. **Extracting all elements greater than 0.5**:
   - Your approach is correct, but using `numpy` operations instead of list comprehension makes the code more concise.
   ```python
   data2 = data[data > 0.5]  # This directly extracts elements > 0.5
   print(f'We get all more than 0.5: {data2}')
   ```

2. **Extracting the 3rd and 5th rows**:
   - The way you add the rows `[data[2] + data[4]]` doesn't produce a clean result. If you want to display them individually:
   ```python
   row_3 = data[2]  # 3rd row (index 2)
   row_5 = data[4]  # 5th row (index 4)
   print(f'3rd row: {row_3}')
   print(f'5th row: {row_5}')
   ```

3. **Replacing elements less than 0.2 with zero**:
   - You're flattening the array, but it's better to modify the original array in-place using `numpy`:
   ```python
   data[data < 0.2] = 0
   print(f'Data after replacing elements < 0.2 with zero:\n{data}')
   ```

4. **Finding the maximum value**:
   - Your approach `np.max(data)` is correct, and there’s nothing to fix here. Good work!

### Complete and Enhanced Code:
Here’s the full solution with improvements:
```python
import numpy as np

# Step 1: Create a 10x10 matrix with random floats between 0.0 and 1.0
data = np.random.uniform(0.0, 1.0, size=(10, 10))
print("Original Matrix:\n", data)

# Step 2: Extract all elements greater than 0.5
data2 = data[data > 0.5]
print(f"\nAll elements > 0.5:\n{data2}")

# Step 3: Extract the 3rd and 5th rows
row_3 = data[2]  # 3rd row
row_5 = data[4]  # 5th row
print(f"\n3rd row: {row_3}")
print(f"5th row: {row_5}")

# Step 4: Replace all elements less than 0.2 with 0
data[data < 0.2] = 0
print("\nMatrix after replacing elements < 0.2 with 0:\n", data)

# Step 5: Find the row with the maximum sum
row_sums = np.sum(data, axis=1)
max_row_index = np.argmax(row_sums)
print(f"\nIndex of the row with the maximum sum: {max_row_index}")
```

### Key Insights:
1. Using `numpy` operations (`data > 0.5` or `data < 0.2`) is more efficient and readable than list comprehensions.
2. It's better to handle rows individually with indexing (`data[2]`, `data[4]`) for clarity.
3. Modifying arrays in-place with NumPy helps maintain the structure and avoids unnecessary flattening or reshaping.

Give this refined version a shot! 😊 Would you like a new problem to try out?