In [1]:
import numpy as np

Alright, here's a fun and slightly more advanced NumPy challenge:

Problem: Image-like Array Manipulation

Create a 10x10 NumPy array of random integers between 0 and 255 to simulate a grayscale image.

Normalize the pixel values to be between 0 and 1.

Replace all pixel values greater than 0.7 with 1.

Divide the array into four quadrants and calculate the average value of each quadrant.

Find the location (row, column) of the pixel with the highest value in the entire array.

Give this one a try! If you solve it, I'd love to see your work. 😊


In [78]:
image = np.random.randint(0.0, 255.0, (10,10))


image_normalized = image /255.0


image_thresholded = np.where(image_normalized > 0.7,1,image_normalized)


#print(image_normalized)
print(image_thresholded)

top_left = image_thresholded[:5,:5]
top_right = image_thresholded[:5,5:]
bottom_left = image_thresholded[5:,:5]
bottom_right = image_thresholded[5:,5:]

av1 = np.mean(top_left)
av2 = np.mean(top_right)
av3 = np.mean(bottom_left)
av4 = np.mean(bottom_right)

max_location = np.unravel_index(np.argmax(image_thresholded),image_thresholded.shape)
print(max_location)

print(f'Q1:{av1}  Q2:{av2}  Q3:{av3} Q4:{av4}')


[[1.         1.         0.38823529 0.18039216 1.         0.10980392
  0.31372549 1.         0.50196078 0.5254902 ]
 [0.07058824 0.04705882 0.45490196 0.36470588 0.07843137 1.
  1.         1.         1.         0.4627451 ]
 [0.14509804 0.04313725 1.         0.33333333 0.15294118 0.02352941
  0.02745098 0.63529412 0.21960784 1.        ]
 [0.01960784 0.5372549  1.         1.         1.         0.05882353
  0.12156863 1.         0.20784314 0.68235294]
 [1.         0.49019608 1.         1.         0.35686275 1.
  0.45490196 0.43137255 1.         0.43137255]
 [1.         0.3254902  0.56470588 1.         0.52156863 0.39215686
  0.52156863 0.6745098  1.         0.23137255]
 [0.20392157 1.         0.30196078 0.64313725 0.11764706 0.23921569
  0.11764706 0.57254902 0.12941176 0.62352941]
 [0.23137255 1.         1.         0.61960784 0.5372549  0.18431373
  0.38823529 0.42745098 1.         0.59607843]
 [0.25882353 1.         0.61176471 0.28627451 1.         0.69019608
  0.44705882 0.11372549 0.43

Alright, here’s a medium-level NumPy challenge for you:

Problem: Logical Indexing and Advanced Calculations

Create a 15x15 matrix with random integers between 1 and 100.

Find all elements that are divisible by 3 and replace them with -1.

Calculate the sum of the elements in each row and identify the row index with the smallest sum.

Create a sub-matrix by extracting all rows from the original matrix where the sum of the row elements is greater than 500.

Flatten the sub-matrix and calculate the median and standard deviation of its elements.

This should test both your problem-solving skills and familiarity with NumPy. Let me know how it goes! 😊



In [90]:
data_15 = np.random.randint(1,100,(15,15))

filterd_data = data_15[]

replace_3_data = [3 if x % 3 == 0 else x for x in data_15.flatten()]
print(replace_3_data)



# replace all 3 to -1
replace_neg1 = [-1 if x == 3 else x for x in replace_3_data]
print(replace_neg1)

print(sum(replace_3_data))

row_sum = sum(replace_3_data)

print(sum(replace_neg1))

submatrix = data_15[row_sum > 500]

print(submatrix)

SyntaxError: invalid syntax (2129584169.py, line 3)

In [42]:
# generate a 15x15 matrix random integer was 1 and 100

import numpy as np

data = np.random.randint(1,101,(15,15))


# replace the elements divisible by 3 with -1

data_replace_3 = np.where(data % 3 == 0, -1, data)

sum_row = np.sum(data_replace_3,axis =1)
min_sum_index = np.argmin(sum_row)


print(data_replace_3)
print(sum_row)
print(min_sum_index)

[[ -1  25  46  -1  -1  56  43   5  -1  -1  -1  23  40  35  92]
 [ -1  20  31  -1  26  58  80  -1  -1  -1  77  89  -1  31  65]
 [ -1  31  94  52  55  83  37   7  -1  16  73  74  76  16  55]
 [ 82  -1   2  29  -1  10  74  70  80  50  17  -1  22  49  22]
 [ 37  -1  -1  50  25  76  14  -1   7  85   2  79  -1  40  -1]
 [ 16  76  -1  -1  92  20  80  -1  53   8  79  20  64  98   5]
 [ 40   7  -1  -1  14  97  53  -1  -1  92  -1   7  -1  80  95]
 [ 95  -1  -1  29  -1  -1  -1  23  83  17  -1  -1  -1  65  -1]
 [ 53  85  -1  -1  76  68  -1   1  94   1  -1  -1  -1  10  -1]
 [ -1 100  92  17  64  32  52  -1  82  97  47  -1  -1  -1  26]
 [  7  34  58  10  31  59  32  52  52   7  62  38  85  28  65]
 [  8  74   2  -1  -1  16  50  97  -1  59  -1  -1  83  17  29]
 [ 44  49  -1  -1  58  -1  11  -1  17  67  55  -1  32  43  -1]
 [ -1  44  32  70  -1  -1  38  40  25  -1  92  -1  -1  -1  -1]
 [ 91  13  31  65  -1  44  50  77  74  41  55  14  65  74  -1]]
[359 471 667 504 410 608 479 303 381 604 620 430 370 3

In [1]:
import pandas as pd


In [2]:
data = {
    'Name': ['John', 'Alice', 'Michael', 'Sarah'],
    'Age': [25, 30, 22, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Miami']
}

In [ ]:
data = {
    'Name': ['John', 'Alice', 'Michael', 'Sarah'],
    'Age': [25, 30, 22, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Miami']
}

df = pd.DataFrame(data)

# Correct filtering
filtered_data = df.filter(items=['Age'])

over_25 = df[filtered_data > 25]

print(over_25)

  Name   Age City
0  NaN   NaN  NaN
1  NaN  30.0  NaN
2  NaN   NaN  NaN
3  NaN  28.0  NaN


In [22]:
data = {
    'Name': ['John', 'Alice', 'Michael', 'Sarah'],
    'Age': [25, 30, 22, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Miami']
}

df = pd.DataFrame(data)

over_25 = df[df['Age']>25]

In [23]:
print(over_25)

    Name  Age         City
1  Alice   30  Los Angeles
3  Sarah   28        Miami


In [25]:
data3 = {
    'Name': ['John', 'Alice', 'Michael', 'Sarah'],
    'Subject': ['Math', 'Science', 'English', 'Math'],
    'Score': [85, 92, 78, 89]
}

df1 = pd.DataFrame(data3)

math_subject =df1[df1['Subject'] == 'Math']
print(math_subject)

    Name Subject  Score
0   John    Math     85
3  Sarah    Math     89


Alright, here's another pandas challenge for you:

You have the following DataFrame called `sales`:

| Product    | Price | Quantity |
|------------|-------|----------|
| Laptop     | 800   | 5        |
| Smartphone | 500   | 10       |
| Tablet     | 300   | 8        |
| Monitor    | 200   | 7        |

**Problem:** Write the code to add a new column called `Total Sales` that calculates the total sales for each product (i.e., `Price` multiplied by `Quantity`).

Have fun with it, and let me know your answer when you're done! 😊

In [34]:
# Data in dictionary format
data = {
    'Product': ['Laptop', 'Smartphone', 'Tablet', 'Monitor'],
    'Price': [800, 500, 300, 200],
    'Quantity': [5, 10, 8, 7]
}

df2 = pd.DataFrame(data)

total_sale = df2['Price'] * df2['Quantity']

df2['Total Sale'] = total_sale

print(df2)

      Product  Price  Quantity  Total Sale
0      Laptop    800         5        4000
1  Smartphone    500        10        5000
2      Tablet    300         8        2400
3     Monitor    200         7        1400


Sure, here’s another pandas problem to challenge your skills:

You have the following DataFrame called `employees`:

| Employee   | Department | Salary | Years of Service |
|------------|------------|--------|------------------|
| John       | HR         | 50000  | 5                |
| Alice      | IT         | 70000  | 8                |
| Michael    | IT         | 65000  | 6                |
| Sarah      | HR         | 52000  | 4                |

**Problem:** Write the code to:
1. Find the average salary of employees in each department.
2. Filter out employees with `Years of Service` less than 5.

Let me know your solutions when you're ready! 😊

In [7]:
import pandas as pd

# Data in dictionary format
data = {
    'Employee': ['John', 'Alice', 'Michael', 'Sarah'],
    'Department': ['HR', 'IT', 'IT', 'HR'],
    'Salary': [50000, 70000, 65000, 52000],
    'Years of Service': [5, 8, 6, 4]
}

df = pd.DataFrame(data)

avg_salary = df.groupby('Department')['Salary'].mean()
filtered_employee =  df[df['Years of Service'] >= 5]

print(avg_salary)
print(filtered_employee)

Department
HR    51000.0
IT    67500.0
Name: Salary, dtype: float64
  Employee Department  Salary  Years of Service
0     John         HR   50000                 5
1    Alice         IT   70000                 8
2  Michael         IT   65000                 6


In [8]:
students = pd.DataFrame({
    'StudentID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Gender': ['F', 'M', 'M', 'M']
})

# Creating the students_scores DataFrame
students_scores = pd.DataFrame({
    'StudentID': [1, 2, 3, 4],
    'Math': [85, 78, 92, 88],
    'English': [90, 82, 85, 87],
    'Science': [88, 79, 93, 90]
})
