In [1]:
import numpy as np

In [13]:
data = np.random.randint(1,100,(5,5))

data[data % 2 == 0 ] = -1

print('this is the even number was replace by -1')
print(data)

data_container = []
data_container_max = []
x = 0

for x in range(5):
    i = sum(data[x])    
    i2 = max(data[x])                          
    data_container.append(i)
    data_container_max.append(i2)

print(f'this is the {data_container}')
print(f'this is max number of each row {data_container_max}')

this is the even number was replace by -1
[[63 -1 -1 -1 -1]
 [97 -1 13 -1 -1]
 [23 -1 -1 51 19]
 [-1 85 -1 75 -1]
 [-1 -1 55 89 -1]]
this is the [59, 107, 91, 157, 141]
this is max number of each row [63, 97, 51, 85, 89]


In [18]:
a = np.array([6, 6])

In [12]:
import scipy
import numpy as np
import statistics
dataset1 = np.array([5,3,8,3,9,3,4,6,8])

print(f'this is the mean {np.mean(dataset1)}')
print(f'this is the meadian {np.median(dataset1)}')
print(f'this is the mode {statistics.mode(dataset1)}')

this is the mean 5.444444444444445
this is the meadian 5.0
this is the mode 3


In [13]:
[ 2x + y - z = 8
-3x - y + 2z = -11
-2x + y + 2z = -3 ]

SyntaxError: invalid decimal literal (563787600.py, line 1)

In [17]:
from scipy.linalg import solve


solution = solve([[2, 1, -1], [-3, -1, 2], [-2, 1, 2]], [8, -11, -3])

# Print the solution
print("Solution:", solution)


Solution: [ 2.  3. -1.]


In [23]:
from scipy.linalg import solve
import numpy as  np
# [ 2x + 3y + 4z = 10 \ -x + 5y - z = 5 \ 3x - y + 2z = 7 ]
data_a = np.array([[2,3,4],[-1,5,-1],[3,-1,2]])
data_b = np.array([10,5,7])



data_c = np.linalg.solve(data_a,data_b)
print(data_c)

[ 2.95121951  1.56097561 -0.14634146]
