In [1]:
import numpy as np

In [6]:
arr = np.array([4,2,3,4,5,4,4])

In [7]:
print(arr)

[4 2 3 4 5 4 4]


In [8]:
x = np.where(arr == 4)

In [9]:
print(x)

(array([0, 3, 5, 6], dtype=int64),)


In [10]:
arr = np.array([1,2,3,4,5,6,7,8])

In [ ]:
x = np.where(arr% 2== 0)

In [11]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

In [18]:
x = np.where(arr%2 == 0)

In [19]:
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [20]:
arr = np.array([1,2,3,4,5,6,7,8])

x = np.where(arr%2 == 1)

In [21]:
import numpy as np

arr = np.array([6,7,8,9])


x = np.searchsorted(arr,7)

print(x)

1


In [25]:
import numpy as np

arr = np.array([6,7,8,9])

x = np.searchsorted(arr,7,side='right')

print(x)

2


In [26]:
import numpy as np

arr = np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [27]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

In [28]:
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [29]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])


for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [32]:
data = np.array([1.5,2.0,3.5])
mean = np.mean(data)
std = np.std(data)


z_scores = (data - mean) / std

print(z_scores)

[-0.98058068 -0.39223227  1.37281295]


In [33]:
data = np.array([5,12,20,7,3])
filtered = data[data > 10]

In [34]:
print(filtered)

[12 20]


In [35]:
import numpy as np

In [39]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [43]:
arr = np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [44]:
arr = np.array([1,2,3,4,5,6,7,8])

newarr = arr.reshape(2,2,-1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [47]:
a = np.array([[1,2],[3,4]])

mean = a.mean(axis=0)
normalized = a - mean

In [49]:
print(normalized)

[[-1. -1.]
 [ 1.  1.]]


In [50]:
data = np.array([50,60,70,40])

labels = np.where(data > 55, 'high','low')

In [51]:
print(labels)

['low' 'high' 'high' 'low']


In [52]:
scores = np.array([70,85,60,45,90])
passed = np.where(scores >= 60,1,0)

print(passed)

[1 1 1 0 1]


In [53]:
matrix = np.array([[10,15],[25,5]])

In [54]:
result = np.where(matrix > 10,1,0)

In [55]:
print(result)

[[0 1]
 [1 0]]


In [56]:
ages = np.array([12,25,17,30,65])
labels = np.where(ages < 18, 'minor','adult')

print(labels)

['minor' 'adult' 'minor' 'adult' 'adult']


In [57]:
scores = np.array([85,40,60,95,30])

grades = np.where(scores >= 75, 'A',
        np.where(scores >= 50, 'B','F'))

In [58]:
print(grades)

['A' 'F' 'B' 'A' 'F']


In [63]:
bmi = np.array([16,21,27,31,19,25])

categories = np.where(bmi < 18.5, 'Underweight',
             np.where(bmi < 25,    'Normal',
             np.where(bmi < 30,   'Overweight','Obese')))

print(categories)

['Underweight' 'Normal' 'Overweight' 'Obese' 'Normal' 'Overweight']


In [64]:
import pandas as pd

df = pd.DataFrame({
    'Age':[15,22,67,45]
})

df['Category'] = np.where(df['Age']< 18, 'Minor','Adult')

print(df)

   Age Category
0   15    Minor
1   22    Adult
2   67    Adult
3   45    Adult


In [65]:
income = np.array([2000,3500,5000,12000])
masked = np.where(income > 4000, 'High','Low')

print(masked)

['Low' 'Low' 'High' 'High']


In [66]:
arr = np.array([10,20,30,40,50])

idx = [1,3,4]

print(arr[idx])

[20 40 50]


In [67]:
arr[idx] = 999
print(arr)

[ 10 999  30 999 999]


In [68]:
matrix = np.array([
    [11,12,13],
    [21,22,23],
    [31,32,33]
])

row_idx = [0,1,2]
col_idx = [1,2,0]

print(matrix[row_idx,col_idx])

[12 23 31]


In [69]:
arr = np.array([10,20,30,40,50])

mask = arr > 30

print(arr[mask])

[40 50]


In [70]:
data = np.array([
    [80,85,90],
    [70,75,80],
    [60,65,70]
])

print(data[data[:,0] > 65])

[[80 85 90]
 [70 75 80]]


In [71]:
arr = np.zeros((3,3),dtype=int)
arr[[0,1,2],[1,2,0]] = 1

print(arr)

[[0 1 0]
 [0 0 1]
 [1 0 0]]


In [72]:
def modify_list(x):
    x.append(100)

my_list = [1,2,3]
modify_list(my_list)

print(my_list)

[1, 2, 3, 100]


In [73]:
def modify_number(n):
    n += 10

x = 5
modify_number(x)
print(x)

5


In [74]:
def update_array(a):
    a[0] = 999

arr = np.array([1,2,3])
update_array(arr)

print(arr)

[999   2   3]


In [75]:
def increment(x):
    x += 1

a = 10
increment(a)
print(a)

10


In [76]:
def add_item(lst):
    lst.append(99)


my_list = [1,2,3]
add_item(my_list)
print(my_list)

[1, 2, 3, 99]


In [77]:
def reset_list(lst):
    lst.clear()

x = [1,2,3]
reset_list(x)
print(x)

[]


In [78]:
def reset_list_safe(lst):
    lst = lst.copy()
    lst.clear()

x = [1,2,3]
reset_list_safe(x)
print(x)

[1, 2, 3]


In [79]:
import numpy as np

a = np.array([1,2,3,4])
b = a[1:3]

b[0] = 999
print(a)

[  1 999   3   4]


In [83]:
def scale(x):
    x *= 100

data = np.ones((1000000,))
scale(data)
print(scale(data))

None


In [81]:
a = np.array([1,2,3])
b = a[1:]
c = a.copy()

np.shares_memory(a,b)
np.shares_memory(a,c)

False

In [84]:
square = lambda x:x * x
print(square(5))

25


In [86]:
def square(x):
    return x * x

print(square(5))

25


In [87]:
add = lambda a,b: a + b
print(add(3,4))

7


In [88]:
students = [('Anna',85),('Bob',90),('Cara',78)]

sorted_students = sorted(students,key=lambda x: x[1])

print(sorted_students)

[('Cara', 78), ('Anna', 85), ('Bob', 90)]


In [89]:
nums = [1,2,3,4]

squared = list(map(lambda x: x * x, nums))
print(squared)

[1, 4, 9, 16]
